/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef SUBSTRCTABLE_H
#define SUBSTRCTABLE_H

/* function declarations */
void init_subsTrcTable(void);
void initialize_table_subsTrcTable(void);
Netsnmp_Node_Handler subsTrcTable_handler;

netsnmp_tdata_row *
subsTrcTable_createEntry(netsnmp_tdata *table_data
                 , long  subsTrcIdType
                 , char* subsTrcIdName
                 , size_t subsTrcIdName_len
                );

#define SUBSTRCTABLE_TIMEOUT  60
#define NAME_MAX_LEN          15

/* column number definitions for table subsTrcTable */
       #define COLUMN_SUBSTRCIDTYPE		1
       #define COLUMN_SUBSTRCIDNAME		2
       #define COLUMN_SUBSTRCLEVEL		3
       #define COLUMN_SUBSTRCTYPE		4
       #define COLUMN_SUBSTRCROWSTATUS		5
#endif /* SUBSTRCTABLE_H */
