/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

void init_subsTrcTable(void);


  
static int keep_running; 
RETSIGTYPE stop_server(int __attribute__((unused)) a) { 
        keep_running = 0; 
} 
  
int main() 
{ 
   const char *app_name = "Test"; 
   /* we are a subagent */ 
   netsnmp_ds_set_boolean(NETSNMP_DS_APPLICATION_ID, NETSNMP_DS_AGENT_ROLE, 1); 
  
   /* initialize the agent library */ 
   init_agent(app_name); 
  
   /* initialize your mib code here */ 
   init_subsTrcTable();  //如果还需添加扩展，只需将生成.c中的init_*()函数添加到此就可以了。
  
   /* Test will be used to read Test.conf files. */ 
   init_snmp(app_name); 
   keep_running = 1; 
   while(keep_running) 
   { 
        agent_check_and_process(1);/* block every 1 second */ 
   } 
   /* at shutdown time */ 
   snmp_shutdown(app_name); 
  
   /* deinitialize your mib code here */ 
  
   /* shutdown the agent library */ 
   shutdown_agent(); 
   return 0; 
}